### ISSUE TITLE
Lambdaguard fails for policy if statement is an object

### ISSUE THREAD

**Issue by nimrodkor** [Skyscanner/LambdaGuard#15]
We have a lambda with the following policy:
```json
{
  "Document": {
    "Version": "2012-10-17",
    "Statement": {
      "Effect": "Allow",
      "Action": [
        "xray:PutTraceSegments",
        "xray:PutTelemetryRecords"
      ],
      "Resource": ["*"]
    }
  },
  "VersionId": "v1",
  "IsDefaultVersion": true
}
```
This causes the following error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/lambdaguard", line 11, in <module>
    load_entry_point('LambdaGuard', 'console_scripts', 'lambdaguard')()
  File "/Users/nimrod/development/lambdaguard/lambdaguard/__init__.py", line 74, in run
    writes = LambdaWrite(args)
  File "/Users/nimrod/development/lambdaguard/lambdaguard/security/LambdaWrite.py", line 66, in __init__
    self.get_writes()
  File "/Users/nimrod/development/lambdaguard/lambdaguard/security/LambdaWrite.py", line 70, in get_writes
    for lambda_arn, actions in self.parse(policy):
  File "/Users/nimrod/development/lambdaguard/lambdaguard/security/LambdaWrite.py", line 105, in parse
    if statement['Effect'] != 'Allow':
TypeError: string indices must be integers
```

**Comment by adeptex** [comment]
Hey @nimrodkor, sorry for getting back to you so late on this. Thanks for reporting, I will investigate.

**Comment by adeptex** [comment]
Fixed by https://github.com/Skyscanner/LambdaGuard/pull/18

Closing this issue but feel free to reopen needed.

**Comment by nimrodkor** [comment]
Hey @adeptex , I can't reopen this issue. Will open a PR soon
