### ISSUE TITLE
AttributeError: 'STS' object has no attribute 'list_policies_granting_service_access'

### ISSUE THREAD

**Issue by scott-mccracken-friday** [Skyscanner/LambdaGuard#23]
We have been facing the following issue since the release of version 2.3.9.

It's running in Jenkins, which uses the withAws() plugin to assume a role in a different AWS account.
This is using a Python Virtual environment on Python 3.7.4.

```
+ pip3 install lambdaguard
Collecting lambdaguard
  Using cached https://files.pythonhosted.org/packages/1f/03/0cd88b8597c3f6aee213ab084f8cd39ac0f95f6922f6678bc8ee33f3b419/LambdaGuard-2.3.9-py3-none-any.whl
Collecting argparse (from lambdaguard)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting requests (from lambdaguard)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting boto3 (from lambdaguard)
  Using cached https://files.pythonhosted.org/packages/ea/4f/a75bf88d30b79e08dd7930d9643aded0a79c9f696b307f353bb33f62cc5b/boto3-1.11.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting s3transfer<0.4.0,>=0.3.0 (from boto3->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/de/6d/27abf73e66a05726dd52fb3a6645417b5dc86d90488b59589296dafbf054/s3transfer-0.3.1-py2.py3-none-any.whl
Collecting botocore<1.15.0,>=1.14.7 (from boto3->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/10/d7/da416c5d6a8c61796dbc37875c886955798ca88385882725049af49d417a/botocore-1.14.7-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.15.0,>=1.14.7->boto3->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from botocore<1.15.0,>=1.14.7->boto3->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.15.0,>=1.14.7->boto3->lambdaguard)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: argparse, chardet, urllib3, certifi, idna, requests, jmespath, six, python-dateutil, docutils, botocore, s3transfer, boto3, lambdaguard
Successfully installed argparse-1.4.0 boto3-1.11.7 botocore-1.14.7 certifi-2019.11.28 chardet-3.0.4 docutils-0.15.2 idna-2.8 jmespath-0.9.4 lambdaguard-2.3.9 python-dateutil-2.8.1 requests-2.22.0 s3transfer-0.3.1 six-1.14.0 urllib3-1.25.8
[Pipeline] sh
+ lambdaguard --input lambda_functions.txt --verbose
Traceback (most recent call last):
  File "/home/jenkins/workspace/project/Job/.pyenv-usr-bin-python3/bin/lambdaguard", line 10, in <module>
    sys.exit(run())
  File "/home/jenkins/workspace/project/Job/.pyenv-usr-bin-python3/lib64/python3.7/site-packages/lambdaguard/__init__.py", line 65, in run
    identity = STS(f'arn:aws:sts:{args.region}', args.profile, args.keys[0], args.keys[1])
  File "/home/jenkins/workspace/project/Job/.pyenv-usr-bin-python3/lib64/python3.7/site-packages/lambdaguard/core/STS.py", line 26, in __init__
    self.acl = ACL(self.caller['Arn'])
  File "/home/jenkins/workspace/project/Job/.pyenv-usr-bin-python3/lib64/python3.7/site-packages/lambdaguard/utils/acl.py", line 24, in __init__
    self.get_permissions()
  File "/home/jenkins/workspace/project/Job/.pyenv-usr-bin-python3/lib64/python3.7/site-packages/lambdaguard/utils/acl.py", line 27, in get_permissions
    service_access_policies = self.client.list_policies_granting_service_access(
  File "/home/jenkins/workspace/project/Job/.pyenv-usr-bin-python3/lib64/python3.7/site-packages/botocore/client.py", line 526, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'STS' object has no attribute 'list_policies_granting_service_access'
```

It still works when using 2.3.8.

**Comment by adeptex** [comment]
Hey @scott-mccracken-friday thanks for reporting this. That function was introduced in LG 2.3.9. I will investigate and get back to you.

**Comment by adeptex** [comment]
ok so the problem happens when using something like:
`arn:aws:sts::0:assumed-role/group/username`

instead of:
`arn:aws:iam::0:user/username`

**Comment by adeptex** [comment]
Fixed by https://github.com/Skyscanner/LambdaGuard/pull/24
