### ISSUE TITLE
cannot print help message

### ISSUE THREAD

**Issue by vlinden-cs** [Skyscanner/LambdaGuard#8]
When running --help this is the error that is returned:

./lambdaguard --help           
Traceback (most recent call last):
  File "./lambdaguard", line 17, in <module>
    lambdaguard.run()
  File "/usr/local/lib/python3.6/dist-packages/lambdaguard/__init__.py", line 64, in run
    args = parse_args(arguments)
  File "/usr/local/lib/python3.6/dist-packages/lambdaguard/utils/cli.py", line 62, in parse_args
    args = argsParser.parse_known_args()[0]
  File "/usr/lib/python3.6/argparse.py", line 1775, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1981, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.6/argparse.py", line 1921, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1849, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.6/argparse.py", line 1033, in __call__
    parser.print_help()
  File "/usr/lib/python3.6/argparse.py", line 2375, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python3.6/argparse.py", line 2381, in _print_message
    file.write(message)
UnicodeEncodeError: 'ascii' codec can't encode character '\xeb' in position 483: ordinal not in range(128)

**Comment by adeptex** [comment]
Hi @vlinden-cs thanks for reporting. Seems that it can't print `ё` in my name :P 
I will check if UTF-8 can be explicitly set in case your terminal uses ASCII by default

**Comment by adeptex** [comment]
Fixed https://github.com/Skyscanner/LambdaGuard/commit/2d316b34a13486cb18d0a8541ca733e9bb2cad32
